# permissions for end users to view hdfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hdfs-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hdfs-operator
    app.kubernetes.io/part-of: hdfs-operator
    app.kubernetes.io/managed-by: kustomize
  name: hdfs-viewer-role
rules:
- apiGroups:
  - hdfs.zncdata.dev
  resources:
  - hdfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hdfs.zncdata.dev
  resources:
  - hdfs/status
  verbs:
  - get
