apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: hdfs-catalog
  namespace: olm
spec:
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
  image: quay.io/zncdatadev/hdfs-operator-catalog:latest
  displayName: hdfs-catalog
  publisher: zncdatadev
  updateStrategy:
    registryPoll:
      interval: 20m
